services:

  authentik-db:
    image: postgres:15
    container_name: kounhany_authentik_db
    restart: always
    environment:
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: authentik2024
      POSTGRES_DB: authentik_db
    volumes:
      - authentik_db_data:/var/lib/postgresql/data
    networks:
      - kounhany_network

  authentik-redis:
    image: redis:7-alpine
    container_name: kounhany_authentik_redis
    restart: always
    networks:
      - kounhany_network

  authentik-server:
    image: ghcr.io/goauthentik/server:2024.2.2
    container_name: kounhany_authentik_server
    restart: always
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik2024
      AUTHENTIK_POSTGRESQL__NAME: authentik_db
      AUTHENTIK_SECRET_KEY: super-secret-key-change-in-prod
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
    ports:
      - "9000:9000"
      - "9443:9443"
    depends_on:
      - authentik-db
      - authentik-redis
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    networks:
      - kounhany_network

  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.2.2
    container_name: kounhany_authentik_worker
    restart: always
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik2024
      AUTHENTIK_POSTGRESQL__NAME: authentik_db
      AUTHENTIK_SECRET_KEY: super-secret-key-change-in-prod
    depends_on:
      - authentik-db
      - authentik-redis
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    networks:
      - kounhany_network

networks:
  kounhany_network:
    driver: bridge

volumes:
  authentik_db_data:
  authentik_media:
  authentik_templates: